In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("/content/Housingdata.csv")

In [ ]:
data.tail()

,id,url,region,price,type
4921,7024971933,https://worcester.craigslist.org/apa/d/fitchbu...,worcester / central MA,1480,apartment
4922,7024959372,https://worcester.craigslist.org/apa/d/hudson-...,worcester / central MA,2155,apartment
4923,7024940732,https://worcester.craigslist.org/apa/d/worcest...,worcester / central MA,1550,apartment
4924,7024932794,https://worcester.craigslist.org/apa/d/worcest...,worcester / central MA,1810,apartment
4925,7024928221,https://worcester.craigslist.org/apa/d/berlin-...,worcester / central MA,1,apartment

In [ ]:
data[['city','state']] = data["region"].str.split(" / ",expand = True)

In [ ]:
data

,id,url,region,price,type,city,state
0,7048591916,https://boston.craigslist.org/gbs/apa/d/waverl...,boston,2450,apartment,boston,None
1,7048584795,https://boston.craigslist.org/bmw/apa/d/concor...,boston,1747,apartment,boston,None
2,7048579724,https://boston.craigslist.org/bmw/apa/d/concor...,boston,1667,apartment,boston,None
3,7038629072,https://boston.craigslist.org/sob/apa/d/stough...,boston,2400,condo,boston,None
4,7039656604,https://southcoast.craigslist.org/apa/d/allsto...,south coast,2350,apartment,south coast,None
...,...,...,...,...,...,...,...
4921,7024971933,https://worcester.craigslist.org/apa/d/fitchbu...,worcester / central MA,1480,apartment,worcester,central MA
4922,7024959372,https://worcester.craigslist.org/apa/d/hudson-...,worcester / central MA,2155,apartment,worcester,central MA
4923,7024940732,https://worcester.craigslist.org/apa/d/worcest...,worcester / central MA,1550,apartment,worcester,central MA
4924,7024932794,https://worcester.craigslist.org/apa/d/worcest...,worcester / central MA,1810,apartment,worcester,central MA
4925,7024928221,https://worcester.craigslist.org/apa/d/berlin-...,worcester / central MA,1,apartment,worcester,central MA

In [ ]:
data.to_csv("Split Table")